# Form implementation generated from reading ui file 'ex22.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 586)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(200, 100, 381, 181))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lineEditgroupbox = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditgroupbox.setGeometry(QtCore.QRect(120, 40, 211, 22))
        self.lineEditgroupbox.setObjectName("lineEditgroupbox")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 71, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdittakeout = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdittakeout.setGeometry(QtCore.QRect(120, 80, 211, 22))
        self.lineEdittakeout.setObjectName("lineEdittakeout")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 71, 16))
        self.label_4.setObjectName("label_4")
        self.lineEditDamaged = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditDamaged.setGeometry(QtCore.QRect(120, 120, 211, 22))
        self.lineEditDamaged.setObjectName("lineEditDamaged")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 40, 331, 41))
        self.label.setObjectName("label")
        self.pushButtonclose = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonclose.setGeometry(QtCore.QRect(200, 320, 93, 28))
        self.pushButtonclose.setObjectName("pushButtonclose")
        self.pushButtonclrar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonclrar.setGeometry(QtCore.QRect(350, 320, 93, 28))
        self.pushButtonclrar.setObjectName("pushButtonclrar")
        self.pushButtonexecute = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonexecute.setGeometry(QtCore.QRect(480, 320, 93, 28))
        self.pushButtonexecute.setObjectName("pushButtonexecute")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 410, 71, 16))
        self.label_5.setObjectName("label_5")
        self.lineEditOutcome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditOutcome.setGeometry(QtCore.QRect(330, 410, 211, 22))
        self.lineEditOutcome.setObjectName("lineEditOutcome")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButtonclose.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_2.setText(_translate("MainWindow", "Group box"))
        self.label_3.setText(_translate("MainWindow", "Take out"))
        self.label_4.setText(_translate("MainWindow", "Damaged"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#0000ff;\">Thanh Thản Company</span></p></body></html>"))
        self.pushButtonclose.setText(_translate("MainWindow", "Close"))
        self.pushButtonclrar.setText(_translate("MainWindow", "Clear"))
        self.pushButtonexecute.setText(_translate("MainWindow", "Execute"))
        self.label_5.setText(_translate("MainWindow", "Outcome"))
