# Form implementation generated from reading ui file 'D:\Kỹ thuật lập trình\KTLT\py\d311224\ex24\ui\MainWindow24.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 761, 501))
        self.groupBox.setObjectName("groupBox")
        self.label1 = QtWidgets.QLabel(parent=self.groupBox)
        self.label1.setGeometry(QtCore.QRect(90, 70, 111, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label1.setFont(font)
        self.label1.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label2.setGeometry(QtCore.QRect(330, 70, 111, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label2.setFont(font)
        self.label2.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label3.setGeometry(QtCore.QRect(580, 70, 111, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label3.setFont(font)
        self.label3.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.label3.setObjectName("label3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(140, 250, 121, 16))
        self.label_4.setObjectName("label_4")
        self.lineEditmachine = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditmachine.setGeometry(QtCore.QRect(330, 250, 321, 22))
        self.lineEditmachine.setObjectName("lineEditmachine")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(140, 310, 121, 16))
        self.label_5.setObjectName("label_5")
        self.lineEditplayer = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditplayer.setGeometry(QtCore.QRect(330, 310, 321, 22))
        self.lineEditplayer.setObjectName("lineEditplayer")
        self.pushButtonrandom = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonrandom.setGeometry(QtCore.QRect(120, 380, 93, 28))
        self.pushButtonrandom.setObjectName("pushButtonrandom")
        self.pushButtonnewgame = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonnewgame.setGeometry(QtCore.QRect(310, 380, 93, 28))
        self.pushButtonnewgame.setObjectName("pushButtonnewgame")
        self.pushButtonexit = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonexit.setGeometry(QtCore.QRect(540, 380, 93, 28))
        self.pushButtonexit.setObjectName("pushButtonexit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButtonexit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Lucky Number"))
        self.label1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\"><br/></span></p></body></html>"))
        self.label2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "machine money"))
        self.label_5.setText(_translate("MainWindow", "player money"))
        self.pushButtonrandom.setText(_translate("MainWindow", "Random"))
        self.pushButtonnewgame.setText(_translate("MainWindow", "New Game"))
        self.pushButtonexit.setText(_translate("MainWindow", "Exit"))
